services:
  - docker

env:
  - TRAVIS_TAG=repository

before_install:
  - docker build -t localnet/aurutilsci .
  - docker run -d -t --name aurutilsci localnet/aurutilsci bash

install:
  - docker cp aurutils/.SRCINFO aurutilsci:/home/pkguser/src
  - docker cp aurutils/PKGBUILD aurutilsci:/home/pkguser/src

before_script:
  - docker cp pkgbuild.sh aurutilsci:/home/pkguser

script:
  - docker exec aurutilsci bash pkgbuild.sh ${TRAVIS_REPO_SLUG} ${TRAVIS_BUILD_ID}

before_deploy:
  - docker cp aurutilsci:/home/pkguser/bin repository

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: repository/*{db,files,gz,xz}
  overwrite: true
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
